--INSERT INTO work.event_log( process_name, event_type, event_date ) VALUES( 'update_dim_respondent', 'start', SYSDATE );  
INSERT INTO work.event_log( process_name, event_type, event_date, max_wh_datemod, run_id ) 
SELECT 'update_dim_respondent', 'start', SYSDATE, MAX(wh_datemod), '@'
FROM wh.dim_respondent;

INSERT INTO wh.dim_respondent ( entity_id, membershipstatusid, date_membership_status_mod ) 
            SELECT f1.entity_id, f1.value, f1.modified_at 
           FROM panel.fvalues1 f1 
           LEFT OUTER JOIN wh.dim_respondent r ON f1.entity_id = r.entity_id 
           WHERE f1.feature_id = 1151 
           AND f1.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ) ) 
           AND r.entity_id IS NULL;

 UPDATE wh.dim_respondent SET firstname = SUBSTRING(value,1,255 USING OCTETS), wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues7 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 7 AND ( firstname IS NULL OR SUBSTRING(value,1,255 USING OCTETS) <> firstname ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET lastname = SUBSTRING(value,1,255 USING OCTETS), wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues7 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 9 AND ( lastname IS NULL OR SUBSTRING(value,1,255 USING OCTETS) <> lastname ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET gender_code_iso = value, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 11 AND ( gender_code_iso IS NULL OR value <> gender_code_iso ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET date_born = value, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues3 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 12 AND ( date_born IS NULL OR value <> date_born ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET country_enum_value_id = value, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 17 AND ( country_enum_value_id IS NULL OR value <> country_enum_value_id ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET email_address = SUBSTRING(value,1,255 USING OCTETS), wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues4 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 30 AND ( email_address IS NULL OR SUBSTRING(value,1,255 USING OCTETS) <> email_address ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET date_membership_started = value, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues3 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 1202 AND ( date_membership_started IS NULL OR value <> date_membership_started ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET date_membership_ended = value, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues3 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 1203 AND ( date_membership_ended IS NULL OR value <> date_membership_ended ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET cityname = SUBSTRING(value,1,255 USING OCTETS), wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues7 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 22653 AND ( cityname IS NULL OR SUBSTRING(value,1,255 USING OCTETS) <> cityname ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET languageid = value, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 37652 AND ( languageid IS NULL OR value <> languageid ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET postcode = CASE WHEN LENGTH(value) = 5 THEN value ELSE NULL END, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues4 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 38582 AND ( postcode IS NULL OR CASE WHEN LENGTH(value) = 5 THEN value ELSE NULL END <> postcode ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET postal_address_home = SUBSTRING(value,1,255 USING OCTETS), wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues4 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 40288 AND ( postal_address_home IS NULL OR SUBSTRING(value,1,255 USING OCTETS) <> postal_address_home ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET is_accessible = value, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 65627 AND ( is_accessible IS NULL OR value <> is_accessible ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET us_state = CASE WHEN LENGTH(value) = 2 THEN value ELSE NULL END, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues4 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 263049 AND ( us_state IS NULL OR CASE WHEN LENGTH(value) = 2 THEN value ELSE NULL END <> us_state ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET paypal_payerid_hash = SUBSTRING(value,1,255 USING OCTETS), wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues4 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 292070 AND ( paypal_payerid_hash IS NULL OR SUBSTRING(value,1,255 USING OCTETS) <> paypal_payerid_hash ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET membershipstatusid = value, date_membership_status_mod = modified_at, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 1151 AND ( membershipstatusid IS NULL OR value <> membershipstatusid ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET verity_status_id = value, verity_status_date = modified_at, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 277249 AND ( verity_status_id IS NULL OR value <> verity_status_id ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET truesample_real_status_id = value, truesample_real_status_date = modified_at, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 409458 AND ( truesample_real_status_id IS NULL OR value <> truesample_real_status_id ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET truesample_unique_status_id = value, truesample_unique_status_date = modified_at, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 409459 AND ( truesample_unique_status_id IS NULL OR value <> truesample_unique_status_id ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 
 UPDATE wh.dim_respondent SET is_b2b = value, b2b_date_modified = modified_at, wh_datemod = CURRENT_TIMESTAMP FROM panel.fvalues1 AS src WHERE wh.dim_respondent.entity_id = src.entity_id AND src.feature_id = 986034 AND ( is_b2b IS NULL OR value <> is_b2b ) AND src.yearmo >= TO_NUMBER( TO_CHAR( ADD_MONTHS( DATE_TRUNC('MONTH', SYSDATE), -1 ), 'YYYYMM' ))   AND src.wh_datemod > CURRENT_DATE - INTERVAL '10 DAY'; 


--INSERT INTO work.event_log( process_name, event_type, event_date ) VALUES( 'update_dim_respondent', 'end', SYSDATE );  
INSERT INTO work.event_log( process_name, event_type, event_date, max_wh_datemod, run_id ) 
SELECT 'update_dim_respondent', 'end', SYSDATE, MAX(wh_datemod), '@'
FROM wh.dim_respondent;